Update alltry

diff --git a/alltry b/alltry
--- a/alltry
+++ b/alltry
@@ -825,7 +825,7 @@ socket = r:TCP_NODELAY=1
 accept = 446
 connect = 127.0.0.1:109
 
-[dropbear]
+[openssh]
 accept = 777
 connect = 127.0.0.1:22
 
@@ -848,6 +848,54 @@ cd
 
 wget https://raw.githubusercontent.com/Vpaproject/-/main/bd && bash bd
 
+clear
+DISTRO=`awk '/^ID=/' /etc/*-release | awk -F'=' '{ print tolower($2) }'`
+SERVER_IP=`ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p'`
+
+# Welcome Message
+echo 'Welcome to KinGmapua Script'
+echo 'Script Version: 0.1'
+echo 'Updated on: 07/08/2021'
+
+# Verify Distro
+if ! [[ $DISTRO == "ubuntu" || $DISTRO == "debian" ]]; then
+	echo 'This script works only on Debian/Ubuntu OS'
+	exit 1
+fi
+
+# Check if root
+if [ "$(id -u)" != "0" ]; then
+   echo "This script must be run as root" 1>&2
+   exit 1
+fi
+
+
+if test -f "/root/.tcat_installed"; then
+	echo 'TunnelCat VPN Software already installed!'
+	exit 1
+fi
+
+#PORT SERVER
+read -e -p 'Input your Server IP: ' -i $SERVER_IP SERVER_IP
+read -e -p 'Input OpenVPN TCP Port: ' -i '4443' OPENVPN_PORT
+read -e -p 'Input Privoxy Port: ' -i '8787' PRIVOXY_PORT
+read -e -p 'Input ohpserver Port: ' -i '7752' OHP_PORT
+read -e -p 'Input stunnel Port: ' -i '443' STUNNEL_PORT
+read -e -p 'Input DNS Tunnel Domain: ' -i 'dns.tunnel.example.com' DNS_TUNNEL_DOMAIN
+
+# Check input
+echo 'Checking Input...'
+if ! [[ $SERVER_IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+	echo 'Server IP is invalid'
+	exit 1
+fi
+
+if ! [[ $OPENVPN_PORT =~ ^[0-9]+$ || $OHP_PORT =~ ^[0-9]+$ || $PRIVOXY_PORT =~ ^[0-9]+$ || $STUNNEL_PORT =~ ^[0-9]+$ ]]; then
+	echo 'Port is invalid'
+	exit 1
+fi
+
+echo 'Proceeding with the installation of dependencies'
 
 # Install Dependencies
 echo 'Installing Dependencies'
@@ -875,7 +923,7 @@ actionsfile user.action
 filterfile default.filter
 filterfile user.filter
 logfile logfile
-listen-address  :8787
+listen-address  :$PRIVOXY_PORT
 toggle 1
 enable-remote-toggle  0
 enable-remote-http-toggle  0
@@ -909,7 +957,7 @@ Description=Daemonize OpenHTTP Puncher Server
 Wants=network.target
 After=network.target
 [Service]
-ExecStart=/usr/local/bin/ohpserver -port 7752 -proxy 127.0.0.1:8787 -tunnel $SERVER_IP:4443
+ExecStart=/usr/local/bin/ohpserver -port $OHP_PORT -proxy 127.0.0.1:$PRIVOXY_PORT -tunnel $SERVER_IP:$OPENVPN_PORT
 Restart=always
 RestartSec=3
 [Install]
@@ -924,7 +972,7 @@ user = nobody
 chroot = /tmp
 pid_file = /var/run/dns2tcp.pid
 domain = $DNS_TUNNEL_DOMAIN
-resources = ovpn:$SERVER_IP:4443
+resources = ovpn:$SERVER_IP:$OPENVPN_PORT
 EOF
 
 # Start Services
@@ -948,6 +996,8 @@ systemctl enable ohpserver
 
 # Installed
 echo '' > /root/.tcat_installed
+cd
+clear
 cd
 clear
 
